name: .NET Build and Test

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore **/*.csproj
      - name: Build
        run: dotnet build **/*.csproj --no-restore
      - name: Test (se houver testes)
        run: |
          if ls **/*Tests.csproj 1> /dev/null 2>&1; then
            dotnet test **/*Tests.csproj --no-build --verbosity normal
          else
            echo "Nenhum projeto de teste encontrado."
          fi
